inherit_from: .rubocop_todo.yml

Metrics/MethodLength:
  Description: 'Avoid methods longer than 25 lines of code.'
  StyleGuide: '#short-methods'
  Enabled: true
  VersionAdded: '0.25'
  VersionChanged: '1.5'
  CountComments: false  # count full line comments?
  Max: 25
  CountAsOne: []
  IgnoredMethods: []
